// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BeforeClose(arg1) {
  return window['go']['main']['App']['BeforeClose'](arg1);
}

export function CreateNewLeaf(arg1, arg2) {
  return window['go']['main']['App']['CreateNewLeaf'](arg1, arg2);
}

export function CreateNewNotebook(arg1, arg2) {
  return window['go']['main']['App']['CreateNewNotebook'](arg1, arg2);
}

export function DeleteLeaf(arg1, arg2) {
  return window['go']['main']['App']['DeleteLeaf'](arg1, arg2);
}

export function DeleteNotebook(arg1, arg2) {
  return window['go']['main']['App']['DeleteNotebook'](arg1, arg2);
}

export function GetActiveLeaf(arg1) {
  return window['go']['main']['App']['GetActiveLeaf'](arg1);
}

export function GetActiveNotebook(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetActiveNotebook'](arg1, arg2, arg3, arg4, arg5);
}

export function GetActiveNotebookPinnedLeafs(arg1) {
  return window['go']['main']['App']['GetActiveNotebookPinnedLeafs'](arg1);
}

export function GetNotebooks(arg1, arg2) {
  return window['go']['main']['App']['GetNotebooks'](arg1, arg2);
}

export function LoginUser(arg1) {
  return window['go']['main']['App']['LoginUser'](arg1);
}

export function LogoutUser(arg1) {
  return window['go']['main']['App']['LogoutUser'](arg1);
}

export function PatchLeafName(arg1, arg2, arg3) {
  return window['go']['main']['App']['PatchLeafName'](arg1, arg2, arg3);
}

export function PatchNotebookName(arg1, arg2, arg3) {
  return window['go']['main']['App']['PatchNotebookName'](arg1, arg2, arg3);
}

export function RegisterUser(arg1) {
  return window['go']['main']['App']['RegisterUser'](arg1);
}

export function SetNewActiveLeaf(arg1, arg2) {
  return window['go']['main']['App']['SetNewActiveLeaf'](arg1, arg2);
}

export function SetNewActiveNotebook(arg1, arg2) {
  return window['go']['main']['App']['SetNewActiveNotebook'](arg1, arg2);
}

export function SetNewStatusLeaf(arg1, arg2) {
  return window['go']['main']['App']['SetNewStatusLeaf'](arg1, arg2);
}

export function SubmitNewPinnedLeaf(arg1, arg2) {
  return window['go']['main']['App']['SubmitNewPinnedLeaf'](arg1, arg2);
}

export function SubmitRemovedPinnedLeaf(arg1, arg2) {
  return window['go']['main']['App']['SubmitRemovedPinnedLeaf'](arg1, arg2);
}

export function UpdateLeaf(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateLeaf'](arg1, arg2, arg3);
}

export function ValidateSession(arg1) {
  return window['go']['main']['App']['ValidateSession'](arg1);
}
