// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function BeforeClose(arg1:context.Context):Promise<void>;

export function InitializeEcho():Promise<void>;
