// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InitializeDatabase() {
  return window['go']['main']['App']['InitializeDatabase']();
}

export function InitializeEcho() {
  return window['go']['main']['App']['InitializeEcho']();
}
